/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface InstagramFeed {
      'captions': boolean;
      'count': number;
      'even': boolean;
      'link': boolean;
      'permalinks': boolean;
      'token': string;
      'user': string;
    }
  }

  interface HTMLInstagramFeedElement extends StencilComponents.InstagramFeed, HTMLStencilElement {}

  var HTMLInstagramFeedElement: {
    prototype: HTMLInstagramFeedElement;
    new (): HTMLInstagramFeedElement;
  };
  interface HTMLElementTagNameMap {
    'instagram-feed': HTMLInstagramFeedElement;
  }
  interface ElementTagNameMap {
    'instagram-feed': HTMLInstagramFeedElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'instagram-feed': JSXElements.InstagramFeedAttributes;
    }
  }
  namespace JSXElements {
    export interface InstagramFeedAttributes extends HTMLAttributes {
      'captions'?: boolean;
      'count'?: number;
      'even'?: boolean;
      'link'?: boolean;
      'permalinks'?: boolean;
      'token'?: string;
      'user'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SmartImage {
      'bg': string;
      'fill': boolean;
      'height': number;
      'preload': string;
      'square': boolean;
      'width': number;
    }
  }

  interface HTMLSmartImageElement extends StencilComponents.SmartImage, HTMLStencilElement {}

  var HTMLSmartImageElement: {
    prototype: HTMLSmartImageElement;
    new (): HTMLSmartImageElement;
  };
  interface HTMLElementTagNameMap {
    'smart-image': HTMLSmartImageElement;
  }
  interface ElementTagNameMap {
    'smart-image': HTMLSmartImageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'smart-image': JSXElements.SmartImageAttributes;
    }
  }
  namespace JSXElements {
    export interface SmartImageAttributes extends HTMLAttributes {
      'bg'?: string;
      'fill'?: boolean;
      'height'?: number;
      'preload'?: string;
      'square'?: boolean;
      'width'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
